---
version: 2

updates:
  - package-ecosystem: github-actions
    schedule:
      interval: daily
      time: "10:30"
      timezone: "Europe/London"
    groups:
      gha-deps:
        patterns:
          - "*"
    directories:
      - "/.github/actions/*"
      - "/.github/workflows"

  - package-ecosystem: npm
    schedule:
      interval: weekly
      time: "10:30"
      timezone: "Europe/London"
    ignore:
      # v2 is commercial or AGPL, we need to stick to v1 as a result.
      - dependency-name: "ua-parser-js"
        update-types: ["version-update:semver-major"]
    directory: "/"
    groups:
      npm:
        patterns:
          - "*"
