name: Main Branch

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'

jobs:
  validate:
    uses: ./.github/workflows/validate.yaml

  publish-next:
    name: Publish Next/Experimental Version
    environment: experimental-package-release
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Set experimental version
        run: |
          npm version --no-git-tag-version "0.0.0-next.$(date +'%Y%m%d').${GITHUB_SHA:0:7}"
          npm run ts:fmt:fix # as npm version, for some reason, reformats package.json

      - name: Publish to npm
        run: npm publish --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
